name: Daily Automated Actions

on:
  schedule:
    - cron: '0 14 * * *'
  push:
    branches:
      - main

jobs:
  daily-run:
    name: 'Runs daily'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Setup Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Automate blog posts
        run: |
          python run.py  --client-secret "${{ secrets.CLIENT_SECRET }}" --credentials-json "${{ secrets.CREDENTIALS_JSON }}" --blog-id "${{ secrets.BLOG_ID }}" --github-repo "${{ secrets.REPO }}" --json-file "${{ secrets.JSON }}"
