name: Daily Automated Actions
on:
  schedule:
    - cron: '0 14 * * *'

jobs:
  daily-run:
    name: 'Runs daily'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Setup Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auotmate blog posts
        run: |
          python run.py --credentials "${{ secrets.credentials }}" --json "${{ secrets.json }}" --repo "${{ secrets.repo }}"
